# Generated by Django 4.1.7 on 2023-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicaodesaude',
            name='gravidade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
